site_name: Cartoview
repo_name: GitHub
repo_url: https://github.com/cartologic/cartoview
edit_uri: ""
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  icon:
    repo: fontawesome/brands/git-alt
extra:
  social:
    - icon: octicons/link-external-16
      link: https://cartoview.net/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/CartoView/
    - icon: fontawesome/brands/github
      link: https://github.com/cartologic/cartoview/
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/cartoview/
copyright: Copyright &copy; 2021 All Rights Reserved by <a href="https://cartologic.com/">Cartologic</a>
